### ISSUE TITLE
Cannot observe now

### ISSUE THREAD

**Issue by baisebaoma** [TreezzZ/LOLOB#1]
刚刚尝试，现在已经无法使用。请问可以更新吗？我有打算使用批处理命令写一个类似的~

**Comment by TreezzZ** [comment]
抱歉，好久没有玩游戏了，现在也没有精力更新了。核心的步骤就是找到当下韩服LOL客户端启动ob文件的参数，然后用批处理或者其他什么语言来自动处理这些参数

**Comment by baisebaoma** [comment]
你好，我参考了你的代码写了一个目前版本可用的，请问可以给其他人试用吗( •̀ ω •́ )✧

**Comment by TreezzZ** [comment]
> 你好，我参考了你的代码写了一个目前版本可用的，请问可以给其他人试用吗( •̀ ω •́ )✧

很棒，可以的
